import { Component, signal } from '@angular/core';
import { Productitem } from '../productitem/productitem';
import { Product } from '../../models/product';

@Component({
  selector: 'app-productlist',
  standalone: true,
  imports: [Productitem],
  templateUrl: './productlist.html',
  styleUrls: ['./productlist.css'],
})
export class Productlist {
  protected readonly products = signal<Product[]>([
    {
      id: 1,
      name: 'Robe traditionnelle Toghu',
      description: 'Tissée à la main, motifs Bamiléké',
      soldPrice: 22000,
      regularPrice: 28000,
      imageUrl: 'assets/images/Products/10138675087.jfif',
      createdAt: new Date('2026-01-15'),
      categories: ['vêtement', 'femme', 'traditionnel'],
    },
    {
      id: 2,
      name: 'Sac en raphia',
      description: 'Tressé en fibre de raphia, fait main',
      soldPrice: 10000,
      regularPrice: 12000,
      imageUrl: 'assets/images/Products/10149427496.jfif',
      createdAt: new Date('2026-02-10'),
      categories: ['accessoire', 'artisanat'],
    },
    {
      id: 3,
      name: 'Chemise en pagne wax',
      description: 'Coupe ajustée, tissu pagne authentique',
      soldPrice: 9500,
      regularPrice: 13000,
      imageUrl: 'assets/images/Products/chemise-hommes-uni-en-slim-a-manches-longues-coupe.webp',
      createdAt: new Date('2026-02-22'),
      categories: ['vêtement', 'homme'],
    },
    {
      id: 4,
      name: 'Veste Toghu brodée',
      description: 'Velours noir brodé de fils dorés',
      soldPrice: 35000,
      regularPrice: 45000,
      imageUrl: 'assets/images/Products/veste-a-manches-cape-avec-ceinture.jpg',
      createdAt: new Date('2026-03-05'),
      categories: ['vêtement', 'traditionnel', 'cérémonie'],
    },
    {
      id: 5,
      name: 'Chaussures en cuir de Maroua',
      description: 'Cuir véritable, finition artisanale',
      soldPrice: 28000,
      regularPrice: 32000,
      imageUrl: 'assets/images/Products/shooz-de-luxe-780x450.jpg',
      createdAt: new Date('2026-03-18'),
      categories: ['chaussure', 'homme', 'cuir'],
    },
    {
      id: 6,
      name: 'Ensemble Kaba Ngondo',
      description: 'Ensemble pagne deux pièces pour femme',
      soldPrice: 18000,
      regularPrice: 24000,
      imageUrl: 'assets/images/Products/331R2JW_A09_1.webp',
      createdAt: new Date('2026-04-02'),
      categories: ['vêtement', 'femme', 'traditionnel'],
    },
    {
      id: 7,
      name: 'Babouches artisanales',
      description: 'Babouches en cuir tressé, faites main',
      soldPrice: 12000,
      regularPrice: 15000,
      imageUrl: 'assets/images/Products/it786-3.png',
      createdAt: new Date('2026-04-20'),
      categories: ['chaussure', 'accessoire', 'artisanat'],
    },
    {
      id: 8,
      name: 'Boubou brodé Ndop',
      description: 'Boubou ample en coton, broderie traditionnelle',
      soldPrice: 30000,
      regularPrice: 38000,
      imageUrl: 'assets/images/Products/71Pv5qp5KFL._AC_UY1000_.jpg',
      createdAt: new Date('2026-05-08'),
      categories: ['vêtement', 'homme', 'traditionnel'],
    },
  ]);
}
