import { Component, signal } from '@angular/core';
import { Productitem } from '../productitem/productitem';
import { Product } from '../../models/product';

@Component({
  selector: 'app-productlist',
  standalone: true,
  imports: [Productitem],
  templateUrl: './productlist.html',
  styleUrls: ['./productlist.css'],
})
export class Productlist {
  protected readonly products = signal<Product[]>([
    {
      id: 1,
      name: 'Masque Tsesah Bamiléké',
      description: 'Masque-cimier en bois sculpté, art royal des Grassfields',
      soldPrice: 45000,
      regularPrice: 60000,
      imageUrl: 'assets/images/Products/artisanat/masque-tsesah.jpg',
      createdAt: new Date('2026-01-12'),
      categories: ['artisanat', 'masque', 'bamiléké'],
    },
    {
      id: 2,
      name: 'Masque éléphant Bamiléké',
      description: 'Tenue de danse perlée Mbap Mteng, société Kuosi',
      soldPrice: 55000,
      regularPrice: 70000,
      imageUrl: 'assets/images/Products/artisanat/masque-elephant-bamileke.jpg',
      createdAt: new Date('2026-01-20'),
      categories: ['artisanat', 'masque', 'perles'],
    },
    {
      id: 3,
      name: 'Masque casque de danse',
      description: 'Masque heaume en bois patiné, région de l’Ouest',
      soldPrice: 38000,
      regularPrice: 48000,
      imageUrl: 'assets/images/Products/artisanat/masque-casque-danse.jpg',
      createdAt: new Date('2026-01-28'),
      categories: ['artisanat', 'masque', 'bois'],
    },
    {
      id: 4,
      name: 'Masque buffle Bamiléké',
      description: 'Masque buffle aux cornes recourbées, cuir et bois',
      soldPrice: 40000,
      regularPrice: 52000,
      imageUrl: 'assets/images/Products/artisanat/masque-buffle-bamileke.jpg',
      createdAt: new Date('2026-02-05'),
      categories: ['artisanat', 'masque', 'bamiléké'],
    },
    {
      id: 5,
      name: 'Statuette de dignitaire Bangwa',
      description: 'Statue en bois sculpté représentant un notable',
      soldPrice: 65000,
      regularPrice: 85000,
      imageUrl: 'assets/images/Products/artisanat/statuette-bangwa.jpg',
      createdAt: new Date('2026-02-14'),
      categories: ['artisanat', 'sculpture', 'bois'],
    },
    {
      id: 6,
      name: 'Sac perlé Bamiléké',
      description: 'Sac de cérémonie brodé de perles et cauris',
      soldPrice: 18000,
      regularPrice: 25000,
      imageUrl: 'assets/images/Products/artisanat/sac-perle-bamileke.jpg',
      createdAt: new Date('2026-02-22'),
      categories: ['artisanat', 'accessoire', 'perles'],
    },
    {
      id: 7,
      name: 'Statue royale perlée Bamoun',
      description: 'Figure cérémonielle entièrement perlée, Foumban',
      soldPrice: 75000,
      regularPrice: 95000,
      imageUrl: 'assets/images/Products/artisanat/trone-bamoun.jpg',
      createdAt: new Date('2026-03-02'),
      categories: ['artisanat', 'sculpture', 'perles'],
    },
    {
      id: 8,
      name: 'Calebasse à vin de palme perlée',
      description: 'Gourde perlée aux motifs géométriques colorés',
      soldPrice: 22000,
      regularPrice: 30000,
      imageUrl: 'assets/images/Products/artisanat/recipient-vin-palme.jpg',
      createdAt: new Date('2026-03-10'),
      categories: ['artisanat', 'décoration', 'perles'],
    },
    {
      id: 9,
      name: 'Repose-tête de prestige sculpté',
      description: 'Appui-nuque en bois aux motifs de serpents entrelacés',
      soldPrice: 28000,
      regularPrice: 38000,
      imageUrl: 'assets/images/Products/artisanat/tabouret-prestige.jpg',
      createdAt: new Date('2026-03-18'),
      categories: ['artisanat', 'mobilier', 'bois'],
    },
    {
      id: 10,
      name: 'Tabouret royal Douala',
      description: 'Tabouret sculpté à la main, bois massif verni',
      soldPrice: 30000,
      regularPrice: 40000,
      imageUrl: 'assets/images/Products/artisanat/tabouret-duala.jpg',
      createdAt: new Date('2026-03-26'),
      categories: ['artisanat', 'mobilier', 'bois'],
    },
    {
      id: 11,
      name: 'Pipe sculptée Bamoun',
      description: 'Pipe en bois et bronze à effigie, travail de Foumban',
      soldPrice: 15000,
      regularPrice: 22000,
      imageUrl: 'assets/images/Products/artisanat/pipe-bamoun.jpg',
      createdAt: new Date('2026-04-03'),
      categories: ['artisanat', 'décoration', 'bamoun'],
    },
    {
      id: 12,
      name: 'Tambour Bamoun sculpté',
      description: 'Tambour en bois aux motifs en relief, peau tendue',
      soldPrice: 35000,
      regularPrice: 45000,
      imageUrl: 'assets/images/Products/artisanat/tambour-bamoun.jpg',
      createdAt: new Date('2026-04-11'),
      categories: ['artisanat', 'musique', 'bois'],
    },
    {
      id: 13,
      name: 'Poterie sacrée Mafa',
      description: 'Jarre en terre cuite façonnée à la main, Monts Mandara',
      soldPrice: 12000,
      regularPrice: 18000,
      imageUrl: 'assets/images/Products/artisanat/poterie-mafa.jpg',
      createdAt: new Date('2026-04-19'),
      categories: ['artisanat', 'poterie', 'terre cuite'],
    },
    {
      id: 14,
      name: 'Tête en terre cuite Sao',
      description: 'Tête modelée d’inspiration Sao, art du Logone',
      soldPrice: 25000,
      regularPrice: 35000,
      imageUrl: 'assets/images/Products/artisanat/tete-sao.jpg',
      createdAt: new Date('2026-04-27'),
      categories: ['artisanat', 'sculpture', 'terre cuite'],
    },
    {
      id: 15,
      name: 'Tissu Ndop indigo',
      description: 'Étoffe royale teinte à l’indigo, motifs Bamoun',
      soldPrice: 20000,
      regularPrice: 28000,
      imageUrl: 'assets/images/Products/artisanat/boubou-ndop.jpg',
      createdAt: new Date('2026-05-05'),
      categories: ['artisanat', 'textile', 'traditionnel'],
    },
  ]);
}
